// <auto-generated />
using System;
using EducaMBAXpert.CatalagoCursos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducaMBAXpert.CatalagoCursos.Data.Migrations
{
    [DbContext(typeof(CursoContext))]
    [Migration("20250426174210_DB_Initial")]
    partial class DB_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("EducaMBAXpert.CatalagoCursos.Domain.Entities.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModuloId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("EducaMBAXpert.CatalagoCursos.Domain.Entities.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("EducaMBAXpert.CatalagoCursos.Domain.Entities.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("EducaMBAXpert.CatalagoCursos.Domain.Entities.Aula", b =>
                {
                    b.HasOne("EducaMBAXpert.CatalagoCursos.Domain.Entities.Modulo", null)
                        .WithMany("Aulas")
                        .HasForeignKey("ModuloId");
                });

            modelBuilder.Entity("EducaMBAXpert.CatalagoCursos.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("EducaMBAXpert.CatalagoCursos.Domain.Entities.Curso", null)
                        .WithMany("Modulos")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("EducaMBAXpert.CatalagoCursos.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("EducaMBAXpert.CatalagoCursos.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
